Amsterdam/meldingen-frontend

- libs/formio/src/components/Textarea/Textarea.tsx
- libs/formio/src/template/input/input.spec.tsx
- libs/formio/src/template/input/input.tsx
Ticket: [SIG-6102](https://gemeente-amsterdam.atlassian.net/browse/SIG-6102)
[SIG-6102]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update character counter

- apps/admin/src/pages/form/utils/filterFormResponse.ts
- apps/admin/src/pages/form/utils/filterFormResponseMocks.ts
- apps/public/next-env.d.ts
- libs/formio/src/components/Textarea/Textarea.tsx
- libs/formio/src/components/Textarea/editForm.ts
- libs/formio/src/template/input/input.spec.tsx
- libs/formio/src/template/input/input.tsx
Ticket: [SIG-6176](https://gemeente-amsterdam.atlassian.net/browse/SIG-6176)
[SIG-6176]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add max character count

- apps/public/.eslintrc.json
- apps/public/package.json
- apps/public/src/app/page.tsx
- libs/api-client/src/schemas.gen.ts
- libs/api-client/src/services.gen.ts
- libs/api-client/src/types.gen.ts
- libs/api-client/tsconfig.json
- pnpm-lock.yaml
> Update to Next 15, fix api calls

- apps/public/src/app/Home.test.tsx
- pnpm-lock.yaml
> Fix lockfile

- .dockerignore
- .gitignore
- Dockerfile
- apps/admin/.env
- apps/admin/src/app/providers/useAuthProvider.ts
- apps/public/next.config.ts
- docker-compose.yml
- libs/api-client/src/core/OpenAPI.ts
- openapi-ts.config.ts
This will dockerize the Admin app
Ticket: [SIG-6337](https://gemeente-amsterdam.atlassian.net/browse/SIG-6337)
[SIG-6337]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Dockerize Admin app

- apps/admin/package.json
- apps/admin/src/app/Admin.tsx
- apps/admin/src/app/providers/useAuthProvider.ts
- pnpm-lock.yaml
> Update ra-keycloak and keycloak-js

- apps/public/src/app/(map)/locatie/kies/_components/BaseLayer.test.tsx
- apps/public/src/app/(map)/locatie/kies/page.tsx
> Fix bug with undefined coordinates

- Dockerfile
- README.md
Ticket: [SIG-6336](https://gemeente-amsterdam.atlassian.net/browse/SIG-6336)
[SIG-6336]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Docker docs, clean up Dockerfile

- apps/public/src/app/(general)/locatie/Locatie.test.tsx
- apps/public/src/app/(general)/locatie/Locatie.tsx
- apps/public/src/app/(general)/locatie/actions.test.tsx
- apps/public/src/app/(general)/locatie/actions.ts
- apps/public/src/app/(map)/locatie/kies/_components/AddressComboBox/AddressComboBox.test.tsx
- apps/public/src/app/(map)/locatie/kies/_components/AddressComboBox/AddressComboBox.tsx
- apps/public/src/app/(map)/locatie/kies/_components/ControlsOverlay/ControlsOverlay.test.tsx
- apps/public/src/app/(map)/locatie/kies/_components/ControlsOverlay/ControlsOverlay.tsx
- apps/public/src/app/(map)/locatie/kies/_components/Map.test.tsx
- apps/public/src/app/(map)/locatie/kies/_components/Map.tsx
- apps/public/src/app/(map)/locatie/kies/_components/SideBar/SideBar.test.tsx
- apps/public/src/app/(map)/locatie/kies/_components/SideBar/SideBar.tsx
- apps/public/src/app/(map)/locatie/kies/_components/SideBar/actions.test.tsx
- apps/public/src/app/(map)/locatie/kies/_components/SideBar/actions.ts
- apps/public/src/app/(map)/locatie/kies/_utils/convertWktPointToCoordinates.test.ts
- apps/public/src/app/(map)/locatie/kies/_utils/convertWktPointToCoordinates.ts
- apps/public/src/app/(map)/locatie/kies/_utils/getAddressFromCoordinates.test.ts
- apps/public/src/app/(map)/locatie/kies/_utils/getAddressFromCoordinates.ts
- apps/public/src/app/(map)/locatie/kies/page.tsx
- apps/public/src/types.d.ts
Tickets: 
- [SIG-6378](https://gemeente-amsterdam.atlassian.net/browse/SIG-6378)
- [SIG-6380](https://gemeente-amsterdam.atlassian.net/browse/SIG-6380)
[SIG-6378]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SIG-6380]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Set marker on map by click on map or input of address in SideBar

- apps/public/src/app/(map)/locatie/kies/_components/Map.tsx
Ticket: [SIG-6379](https://gemeente-amsterdam.atlassian.net/browse/SIG-6379)
[SIG-6379]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add zoom to marker on map

- apps/public/src/app/(map)/locatie/kies/_components/ControlsOverlay/ControlsOverlay.test.tsx
- apps/public/src/app/(map)/locatie/kies/_components/ControlsOverlay/ControlsOverlay.tsx
- apps/public/src/app/(map)/locatie/kies/_components/Map.tsx
Ticket: [SIG-6391](https://gemeente-amsterdam.atlassian.net/browse/SIG-6391)
[SIG-6391]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Current location-button sets coordinates, which in turn shows address and marker

- apps/public/src/app/(map)/locatie/kies/_components/AssetList/AssetList.module.css
- apps/public/src/app/(map)/locatie/kies/_components/Combobox/Combobox.module.css
- apps/public/src/app/(map)/locatie/kies/_components/ControlsOverlay/ControlsOverlay.module.css
- apps/public/src/app/(map)/locatie/kies/_components/Map.module.css
- apps/public/src/app/(map)/locatie/kies/_components/SideBar/SideBar.module.css
- apps/public/src/app/(map)/locatie/kies/_components/SideBar/SideBar.tsx
- apps/public/src/app/(map)/locatie/kies/layout.tsx
- apps/public/src/app/(map)/locatie/kies/page.module.css
- apps/public/src/app/(map)/locatie/kies/page.tsx
Ticket: [SIG-6398](https://gemeente-amsterdam.atlassian.net/browse/SIG-6398)
[SIG-6398]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix map layout

- apps/public/src/app/(map)/locatie/kies/_utils/getAddressFromCoordinates.test.ts
- apps/public/src/app/(map)/locatie/kies/_utils/getAddressFromCoordinates.ts
- apps/public/src/mocks/handlers.ts
Ticket: [SIG-6381](https://gemeente-amsterdam.atlassian.net/browse/SIG-6381)
[SIG-6381]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add pin location on map

- apps/public/src/app/(map)/locatie/kies/page.module.css
Ticket: [SIG-6405](https://gemeente-amsterdam.atlassian.net/browse/SIG-6405)
[SIG-6405]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Set min-height to map

- apps/back-office/src/app/_authentication/authOptions.ts
- apps/back-office/src/app/melding/[meldingId]/Detail.tsx
- apps/back-office/src/app/melding/[meldingId]/page.tsx
Ticket: [SIG-6417](https://gemeente-amsterdam.atlassian.net/browse/SIG-6417)
[SIG-6417]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Melding detail page

- apps/back-office/src/app/Overview.module.css
- apps/back-office/src/app/Overview.test.tsx
- apps/back-office/src/app/Overview.tsx
- apps/back-office/src/app/constants.ts
- apps/back-office/src/app/global.css
- apps/back-office/src/app/layout.tsx
- apps/back-office/src/app/page.test.tsx
- apps/back-office/src/app/page.tsx
- apps/back-office/src/mocks/data.ts
- apps/back-office/src/mocks/endpoints.ts
- apps/back-office/src/mocks/handlers.ts
Ticket: [SIG-6512](https://gemeente-amsterdam.atlassian.net/browse/SIG-6512)
[SIG-6512]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add pagination to back office

- apps/public/src/app/(map)/locatie/kies/SelectLocation.test.tsx
- apps/public/src/app/(map)/locatie/kies/SelectLocation.tsx
Ticket: [SIG-6414](https://gemeente-amsterdam.atlassian.net/browse/SIG-6414)
[SIG-6414]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Hide mobile list view on large screens

- apps/public/src/app/(general)/aanvullende-vragen/[classification]/[panelId]/actions.test.ts
- apps/public/src/app/(general)/aanvullende-vragen/[classification]/[panelId]/actions.ts
- apps/public/src/mocks/endpoints.ts
The MSW endpoint looks a little odd here, I'll fix that in [this PR](https://github.com/Amsterdam/meldingen-frontend/pull/817)
> Fix additional questions error handling, add tests

- .github/workflows/ci.yml
- apps/admin/vite.config.ts
- apps/back-office/vite.config.ts
- apps/melding-form/vite.config.ts
- libs/form-renderer/vite.config.ts
- libs/markdown-to-html/vite.config.ts
- libs/ui/vite.config.ts
Ticket: [SIG-6463](https://gemeente-amsterdam.atlassian.net/browse/SIG-6463)
[SIG-6463]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add test coverage threshold

- apps/back-office/src/app/melding/[meldingId]/utils.test.tsx
- apps/back-office/src/app/melding/[meldingId]/utils.ts
- apps/back-office/translations/nl.json
Ticket: [SIG-6572](https://gemeente-amsterdam.atlassian.net/browse/SIG-6572)
[SIG-6572]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Show fallback text when there is no contact data

- apps/melding-form/src/app/(map)/locatie/kies/_components/Crosshair/Crosshair.module.css
- apps/melding-form/src/app/(map)/locatie/kies/_components/Crosshair/Crosshair.test.tsx
- apps/melding-form/src/app/(map)/locatie/kies/_components/Crosshair/Crosshair.tsx
- apps/melding-form/src/app/(map)/locatie/kies/_components/Map.module.css
- apps/melding-form/src/app/(map)/locatie/kies/_components/Map.tsx
Ticket: [SIG-6606](https://gemeente-amsterdam.atlassian.net/browse/SIG-6606)
[SIG-6606]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Change crosshair icon

- Dockerfile
- apps/back-office/.env
- apps/back-office/src/app/_authentication/authOptions.ts
- apps/back-office/src/app/_authentication/node-env.d.ts
- docker-compose.yml
Ticket: [SIG-6567](https://gemeente-amsterdam.atlassian.net/browse/SIG-6567)
[SIG-6567]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Docker config for backoffice with dynamic keycloak config

- apps/melding-form/src/app/(general)/actions.test.ts
- apps/melding-form/src/app/(general)/actions.ts
Ticket: [SIG-6647](https://gemeente-amsterdam.atlassian.net/browse/SIG-6647)
[SIG-6647]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Show API errors on Home

- apps/melding-form/src/app/(map)/locatie/kies/_components/Map/utils/addAssetLayerToMap.ts
Ticket: [SIG-6717](https://gemeente-amsterdam.atlassian.net/browse/SIG-6717)
[SIG-6717]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove tabfocus from asset markers

- docs/0007-forms.md
- docs/0011-error-handling.md
Ticket: [SIG-6584](https://gemeente-amsterdam.atlassian.net/browse/SIG-6584)
[SIG-6584]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add error handling docs

- apps/back-office/next-env.d.ts
- apps/melding-form/next-env.d.ts
- eslint.config.mjs
- libs/form-builder/package.json
- libs/form-builder/src/FormBuilder.tsx
- pnpm-lock.yaml
> Remove old formiojs package and update next generated files

- apps/melding-form/src/app/(map)/locatie/kies/_components/Combobox/Combobox.tsx
Ticket: [SIG-6734](https://gemeente-amsterdam.atlassian.net/browse/SIG-6734)
[SIG-6734]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Make sure Combobox rerenders when address is set using keyboard on map

- apps/melding-form/src/app/(general)/bijlage/Attachments.module.css
> Remove obsolete fileList class

- apps/melding-form/src/app/(general)/samenvatting/utils.test.ts
- apps/melding-form/src/app/(general)/samenvatting/utils.ts
> Allow classification to not have additional questions on Summary page
